steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'PAYLOAD_SECRET=${_PAYLOAD_SECRET}',
        '--build-arg',
        'DATABASE_URI=${_DATABASE_URI}',
        '-t',
        'gcr.io/$PROJECT_ID/blog-payload-cms:$COMMIT_SHA',
        '.',
      ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/blog-payload-cms:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'payload-blog'
      - '--image'
      - 'gcr.io/$PROJECT_ID/blog-payload-cms:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--port'
      - '3000'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '0'
options:
  automapSubstitutions: true
images:
  - 'gcr.io/$PROJECT_ID/blog-payload-cms:$COMMIT_SHA'
